from enum import Enum


class CalculationOp(str, Enum):
    CALCULATION_OP_AVG = "CALCULATION_OP_AVG"
    CALCULATION_OP_COUNT = "CALCULATION_OP_COUNT"
    CALCULATION_OP_MAX = "CALCULATION_OP_MAX"
    CALCULATION_OP_MIN = "CALCULATION_OP_MIN"
    CALCULATION_OP_P50 = "CALCULATION_OP_P50"
    CALCULATION_OP_P95 = "CALCULATION_OP_P95"
    CALCULATION_OP_P99 = "CALCULATION_OP_P99"
    CALCULATION_OP_SUM = "CALCULATION_OP_SUM"
    CALCULATION_OP_UNSPECIFIED = "CALCULATION_OP_UNSPECIFIED"

    def __str__(self) -> str:
        return str(self.value)
